language: d
d:
- dmd
sudo: false
addons:
  apt:
    packages:
    - libevent-dev
before_install:
- pip install --user codecov
- dub fetch packageversion
script: dub build --compiler=${DC} && dub test --compiler=${DC} --coverage && dub
  build --compiler=${DC} --build=ddox
after_success: codecov
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: "$GH_REPO_TOKEN"
  verbose: true
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: IBmHPYDOY2A60ag0F12QslnDM1b4/jti7sS6TKT55RWr4HE7TP7W3cO38szf81yFTCf1q/1GWwUkRqYkwV+STwkZ9uZXSdLx/jtN2ygzefBSgJK19k7HwQZbp3rSW4UqvOxM1hUjaBLMjKvDFUx1CYSuicmGau7+JQwVFPrTKWV8hzqKZL8q9ens41StNh2R647/PFmWy59kGJu0Dg5PBf+dEhxFB+ZSTH8oNodNEO5siYRwWEMFj2T8xboxtrU6KF3rK+kb23gDRl/fhnyb0QUb9UwjXqN6EAJ78UR3R9AfPiK84M3cuxAsDHCvvXfZhamz8WvoZUWu72fVYmp+rFdRl6H+THSWnwzIVjomFGeo1e/uXdSCo41ZKB2fbUJy8JCJG351AvlpGLO+4rkgsiYimOKawU2p8KLlU2WC/vLfF7oVqkRopuZA9LU1E6foex/smPbSNL0uEm26dVn2rCQ+x7lA1iaQdLxh+jtbdIqsgHU+cdRcl1xS5nwPKrKVX3wPDeICkQf7YK62MzMMI1asOstQbie4j8iyqoSVF1yurdV4/lvIHTvGbU3nngZBwjHNX2I6X8duZMQScYPAiIazQy82zp6VQKJzNhkUNbLJ9g6D7dTnV3e8tcCoytUzBt79wwrHxPJ1a6QFlwSYMoAT5hBwmlzi5AS/lH5jEhQ=
