// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'asciitable.packageversion', kind: "module", path: './asciitable/packageversion.html', attributes: []},
{name: 'asciitable.packageversion.LICENSE', kind: "variabledeclaration", path: './asciitable/packageversion/LICENSE.html', attributes: []},
{name: 'asciitable.packageversion.NAME', kind: "variabledeclaration", path: './asciitable/packageversion/NAME.html', attributes: []},
{name: 'asciitable.packageversion.VERSION', kind: "variabledeclaration", path: './asciitable/packageversion/VERSION.html', attributes: []},
{name: 'asciitable', kind: "module", path: './asciitable.html', attributes: []},
{name: 'asciitable.AsciiTable', kind: "structdeclaration", path: './asciitable/AsciiTable.html', attributes: []},
{name: 'asciitable.AsciiTable.add', kind: "functiondeclaration", path: './asciitable/AsciiTable.add.html', attributes: []},
{name: 'asciitable.AsciiTable.minimumWidths', kind: "variabledeclaration", path: './asciitable/AsciiTable.minimumWidths.html', attributes: []},
{name: 'asciitable.AsciiTable.rows', kind: "variabledeclaration", path: './asciitable/AsciiTable.rows.html', attributes: []},
{name: 'asciitable.AsciiTable.this', kind: "functiondeclaration", path: './asciitable/AsciiTable.this.html', attributes: []},
{name: 'asciitable.AsciiTable.toString', kind: "functiondeclaration", path: './asciitable/AsciiTable.toString.html', attributes: []},
{name: 'asciitable.Row', kind: "structdeclaration", path: './asciitable/Row.html', attributes: []},
{name: 'asciitable.Row.columns', kind: "variabledeclaration", path: './asciitable/Row.columns.html', attributes: []},
{name: 'asciitable.Row.this', kind: "functiondeclaration", path: './asciitable/Row.this.html', attributes: []},
];
